Feat/setup-fork: Update import paths, add parameters, automate
newscorp-ghfb/okta-kubectl-auth pull request #1
Opened 2019-02-08 17:10 UTC by gilmoregrills

### Big PR:
- Updated all the local import paths and stuff like that to newscorp-ghfb from jetstack  
- Added the `--kubeconfig` and `--username` parameters and methods to use them
- Automated the browser-opening and kubectl-configuring steps using the above parameters

2019-02-11 15:50 UTC, gilmoregrills commented
this project was set up to use [goreleaser](https://goreleaser.com/) to handle releases, so once this is merged we can try using that to build all the binaries and push them to the releases tab here

2019-02-13 11:26 UTC, gilmoregrills commented
@marcincuber tested it a bunch and it actually works now! Ready for review 🎉

2019-02-22 14:18 UTC, marcincuber requested changes
See my comments. In general looks good. Error handling doesn't work as expected so take a look into it. One example is execution of okta-kubectl-auth on its own; returns an error because file cluster_config.json doesn't exist.

Also, in terms of docs please add commands how to pull and build the cli locally.

2019-02-22 14:18 UTC, marcincuber commented on Makefile
> -	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -X main.version=$(CI_COMMIT_TAG) -X main.commit=$(CI_COMMIT_SHA) -X main.date=$(shell date -u +%Y-%m-%dT%H:%M:%SZ)' -o okta
Any chances to build both binaries or have steps for both i.e go_build_mac and go_build_linux?

2019-02-22 14:18 UTC, marcincuber commented on README.md
> +####Running the tool:
fix formatting

2019-02-22 14:18 UTC, marcincuber commented on README.md
> +okta-kubectl-auth --client-id=<client-id> --client-secret=<client-secret> --base-domain=<issuer-uri> --kubeconfig <kubeconfig_path> --username <username>
Can we clarify bit better what username is as generally it is misleading? Or perhaps some valid examples

2019-02-22 14:18 UTC, marcincuber commented on README.md
> +
remove empty lines

2019-02-22 14:18 UTC, marcincuber commented on cmd/root.go
> +    Username     string
indent

2019-02-22 14:18 UTC, marcincuber commented on cmd/root.go
> +        o.ClientSecret = flags.ClientSecret
indent

2019-02-22 14:18 UTC, marcincuber commented on pkg/okta/okta.go
> +func (o *Okta) executeKubectlConfiguration(refreshToken string) {
Fix formatting in this function

2019-02-22 14:18 UTC, marcincuber commented on cmd/root.go
> +	RootCmd.PersistentFlags().StringVar(&flags.InputConfig, "config", "cluster_config.json", "Path to a json file containing the required keys/tokens. (see README)")
You shouldn't have a default value set to cluster_config.json. I think this is breaking cli in terms of error handling. 
Also take into account that currently only required flag(s) are "base-domain", "client-id", "client-secret". 

I would expect that you also need to better handle parsing of the file in newOkta() function.

2019-03-13 11:28 UTC, marcincuber approved these changes

2019-03-13 11:28 UTC, merged